Completed base requirements of React.js - Validated Input Component
ChrisGitmed/c1020-code-solutions pull request #125
Opened 2020-12-14 02:17 UTC by ChrisGitmed

![react-validated-input-component](https://user-images.githubusercontent.com/71002706/102033103-6def5e00-3d6f-11eb-8f5f-63b2d19bce5e.gif)

2020-12-14 02:18 UTC, ChrisGitmed commented
Still finishing up the extra functionality.

2020-12-14 04:33 UTC, thebearingedge requested changes
Overall great, except one no-no.

2020-12-14 04:33 UTC, thebearingedge commented on react-validated-input-component/dist/styles.css
> +}
🤮 if these are defined in a library 🙅

2020-12-16 03:32 UTC, thebearingedge requested changes

2020-12-16 03:32 UTC, thebearingedge commented on react-validated-input-component/src/validated-input.jsx
> +    }
I strongly recommend making separate methods to check each of these. They can return `null` or an error message string.

```js
isLongEnough() {

}

hasDigit() {

}

hasSpecialCharacter() {

}
```

Then you can call them in your render method and pick your icon based on the truthiness of the error message.

2020-12-16 22:44 UTC, ChrisGitmed commented
Still need to complete!

2020-12-18 02:25 UTC, thebearingedge requested changes
Nice! one tiny tweak

2020-12-18 02:25 UTC, thebearingedge commented on react-validated-input-component/dist/styles.css
> +}
We don't want to style 3rd-party classes.

2020-12-18 03:19 UTC, thebearingedge approved these changes

2020-12-18 17:56 UTC, merged