Working with collections
ChrisGitmed/c1020-code-solutions pull request #60
Opened 2020-10-25 07:39 UTC by ChrisGitmed

<img width="944" alt="Screen Shot 2020-10-25 at 12 36 38 AM" src="https://user-images.githubusercontent.com/71002706/97101396-5a225800-165a-11eb-8825-12963e5c167d.png">

2020-11-11 21:24 UTC, uzair-ashraf requested changes

2020-11-11 21:24 UTC, uzair-ashraf commented on working-with-collections/main.js
> +}
The problem with this take is that each player will get one of the same card, when you draw cards from a deck, you don't share the same cards right?

2020-11-19 21:32 UTC, thebearingedge requested changes

2020-11-19 21:32 UTC, thebearingedge commented on working-with-collections/main.js
> +var cards = [
Please try to generate the deck with loops.

2020-11-20 19:24 UTC, thebearingedge requested changes

2020-11-20 19:24 UTC, thebearingedge commented on working-with-collections/main.js
> +  }
since the value is _derived_ from the rank, avoid storing the value.

```js
var ranks = [2, 3, 4, 5, 6, 7, 8, 9, 10, 'jack', 'queen', 'king', 'ace']
```

You can define a function that takes hand and returns a score when deciding who wins.

2020-11-20 21:18 UTC, thebearingedge approved these changes

2020-11-20 21:22 UTC, merged