Completed JavaScript - Carousel
ChrisGitmed/c1020-code-solutions pull request #67
Opened 2020-11-05 01:04 UTC by ChrisGitmed

![javascript-carousel](https://user-images.githubusercontent.com/71002706/98184687-d2411700-1ebf-11eb-8cc7-402a3ebc8572.gif)

2020-11-05 01:12 UTC, codingcodymiller requested changes

2020-11-05 01:12 UTC, codingcodymiller commented on javascript-carousel/main.js
> +$dotList[0].addEventListener('click', function (event) {
You could REALLY benefit from some event delegation here. Rather than putting your event handler on each individual dot, try applying it to their parent element, and listen for click events coming from the dot elements 🤓

2020-11-05 01:12 UTC, codingcodymiller commented on javascript-carousel/main.js
> +  if (imageCounter > 0) {
What if it is zero? Can we not move backwards the same way as forwards? You should make the carousel able to loop around either forwards or backwards 👍

2020-11-14 19:50 UTC, thebearingedge requested changes

2020-11-14 19:50 UTC, thebearingedge commented on javascript-carousel/main.js
> +  }
A lot of this could be simplified if you:
1. used a data model to store your image sources and pokemon names _or_
2. put all of your images in the HTML and used a loop to "swap" in the correct image.

2020-11-21 00:23 UTC, thebearingedge requested changes

2020-11-21 00:23 UTC, thebearingedge commented on javascript-carousel/main.js
> +}
Try combining these functions.

2020-11-21 00:23 UTC, thebearingedge commented on javascript-carousel/main.js
> +  resetInterval();
If you move your calls to `resetInterval()` into your function that updates the image and dots, you won't have to repeat it so much.

2020-11-21 00:23 UTC, thebearingedge commented on javascript-carousel/main.js
> +  }
If you base your bounds off of the length of your images array, supporting another image will just mean adding an object to the array instead of also updating these "magic numbers".

https://en.wikipedia.org/wiki/Magic_number_(programming)#:~:text=The%20term%20magic%20number%20or,1%20manuals%20of%20the%201960s.

2020-11-21 00:57 UTC, thebearingedge approved these changes
Bravissimo

2020-11-21 00:58 UTC, merged